authtoken: 2awjQVx7A8NXcv6wGzCSRH3jg82_79D46uQXv7BnajfFTexKi
version: 2
console_ui: true
console_ui_color: transparent
log_level: info
tunnels:
  container:
    proto: http
    addr: host.docker.internal:5000

